apiVersion: v1
kind: Service
metadata:
  name: {{ include "isitok.fullname" . }}
  labels:
    {{- include "isitok.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.target_port }}
      protocol: TCP
  selector:
    {{- include "isitok.selectorLabels" . | nindent 4 }}
